
FROM devlikeapro/waha:chrome

ENV WHATSAPP_API_KEY=omnix-cafe-2024
ENV WHATSAPP_SWAGGER_ENABLED=true
ENV WAHA_DASHBOARD_ENABLED=true
ENV WAHA_DASHBOARD_USERNAME=admin
ENV WAHA_DASHBOARD_PASSWORD=omnix2024

ENV WHATSAPP_API_KEY=omnix-cafe-2024
ENV WHATSAPP_SWAGGER_ENABLED=true
ENV WAHA_DASHBOARD_ENABLED=true
ENV WAHA_DASHBOARD_USERNAME=admin
ENV WAHA_DASHBOARD_PASSWORD=omnix2024
