version: '3'
services:
  waha:
    image: devlikeapro/waha:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_API_KEY=omnix-cafe-2024
      - WHATSAPP_SWAGGER_ENABLED=true
    volumes:
      - waha_data:/app/.sessions
volumes:
  waha_data:
