ervices:
  - type: web
    name: waha-cafeteria
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: WHATSAPP_API_KEY
        value: omnix-cafe-2024
      - key: WHATSAPP_SWAGGER_ENABLED
        value: "true"
      - key: WAHA_DASHBOARD_ENABLED
        value: "true"
      - key: WAHA_DASHBOARD_USERNAME
        value: admin
      - key: WAHA_DASHBOARD_PASSWORD
        sync: false
